In [2]:
import torch
import torch.nn as nn

In [16]:
input = torch.randint(5,(4,3),dtype=torch.float32)
input

tensor([[4., 1., 1.],
        [1., 2., 1.],
        [4., 4., 0.],
        [2., 3., 2.]])

In [12]:
batch_nor = nn.BatchNorm1d(num_features=3)

In [13]:
batch_nor.weight

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [14]:
batch_nor.bias

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

In [17]:
output = batch_nor(input)
output

tensor([[ 0.9622, -1.3416,  0.0000],
        [-1.3471, -0.4472,  0.0000],
        [ 0.9622,  1.3416, -1.4142],
        [-0.5773,  0.4472,  1.4142]], grad_fn=<NativeBatchNormBackward0>)