#Convolutional operation

In [20]:
import torch
import torch.nn as nn

In [21]:
input = torch.randint(5,(1,6,6),dtype=torch.float32) #initialize a tensor with 1 channel,6x6 matrix
input

tensor([[[2., 0., 1., 1., 4., 0.],
         [3., 0., 3., 1., 0., 2.],
         [4., 3., 3., 2., 1., 3.],
         [2., 0., 3., 4., 2., 2.],
         [1., 1., 4., 3., 3., 4.],
         [3., 3., 0., 0., 3., 1.]]])

In [22]:
#define convolution layers
conv_layer = nn.Conv2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 3,
    bias = False
    #What is mean of bias value ?
)

In [28]:
#define convolution layers
conv_layer1 = nn.Conv2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 3,
    bias = 2
    #What is mean of bias value ?
)

In [33]:
#define convolution layers
conv_layer2 = nn.Conv2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 3,
    bias = 2,
    padding = 'same' # find padding size such that output size = input size
    #What is mean of bias value ?
)

In [23]:
conv_layer.weight
#why this is need requires_grad = True ?

Parameter containing:
tensor([[[[ 0.2521, -0.0533,  0.1446],
          [ 0.3314, -0.3178, -0.1751],
          [ 0.2681,  0.0965,  0.1212]]]], requires_grad=True)

In [24]:
init_kernal_weight = torch.randint(
    0, # low
    2, # high
    size = (conv_layer.weight.data.shape), # size
    dtype = torch.float32
)

In [25]:
init_kernal_weight

tensor([[[[0., 0., 1.],
          [1., 0., 1.],
          [0., 0., 0.]]]])

In [29]:
conv_layer.weight.data =init_kernal_weight
conv_layer1.weight.data =init_kernal_weight
conv_layer.weight

Parameter containing:
tensor([[[[0., 0., 1.],
          [1., 0., 1.],
          [0., 0., 0.]]]], requires_grad=True)

In [30]:
output = conv_layer(input)
output #no bias

tensor([[[ 7.,  2.,  7.,  3.],
         [10.,  6.,  4.,  7.],
         [ 8.,  6.,  6.,  9.],
         [ 8.,  8.,  9.,  9.]]], grad_fn=<SqueezeBackward1>)

In [31]:
output = conv_layer1(input) #bias = 2

In [32]:
output

tensor([[[ 7.2092,  2.2092,  7.2092,  3.2092],
         [10.2092,  6.2092,  4.2092,  7.2092],
         [ 8.2092,  6.2092,  6.2092,  9.2092],
         [ 8.2092,  8.2092,  9.2092,  9.2092]]], grad_fn=<SqueezeBackward1>)

In [34]:
conv_layer2.weight.data =init_kernal_weight
output = conv_layer2(input)
output

tensor([[[-0.0262,  2.9738,  0.9738,  4.9738,  0.9738,  3.9738],
         [-0.0262,  6.9738,  1.9738,  6.9738,  2.9738, -0.0262],
         [ 2.9738,  9.9738,  5.9738,  3.9738,  6.9738,  0.9738],
         [ 2.9738,  7.9738,  5.9738,  5.9738,  8.9738,  1.9738],
         [ 0.9738,  7.9738,  7.9738,  8.9738,  8.9738,  2.9738],
         [ 3.9738,  6.9738,  5.9738,  5.9738,  4.9738,  2.9738]]],
       grad_fn=<SqueezeBackward1>)

In [35]:
#define convolution layers
conv_layer3 = nn.Conv2d(
    in_channels = 1,
    out_channels = 1,
    kernel_size = 3,
    bias = 2,
    padding = (2,1)
    #What is mean of bias value ?
)

In [36]:
conv_layer3.weight.data =init_kernal_weight
output = conv_layer3(input)
output

tensor([[[ 0.0811,  0.0811,  0.0811,  0.0811,  0.0811,  0.0811],
         [ 0.0811,  3.0811,  1.0811,  5.0811,  1.0811,  4.0811],
         [ 0.0811,  7.0811,  2.0811,  7.0811,  3.0811,  0.0811],
         [ 3.0811, 10.0811,  6.0811,  4.0811,  7.0811,  1.0811],
         [ 3.0811,  8.0811,  6.0811,  6.0811,  9.0811,  2.0811],
         [ 1.0811,  8.0811,  8.0811,  9.0811,  9.0811,  3.0811],
         [ 4.0811,  7.0811,  6.0811,  6.0811,  5.0811,  3.0811],
         [ 3.0811,  0.0811,  0.0811,  3.0811,  1.0811,  0.0811]]],
       grad_fn=<SqueezeBackward1>)

#Pooling layer

In [37]:
input = torch.randint(
    high = 5,
    size = (1,6,6),
    dtype = torch.float32
)
input

tensor([[[1., 1., 2., 0., 0., 3.],
         [3., 2., 4., 1., 2., 4.],
         [0., 0., 0., 4., 0., 4.],
         [4., 4., 2., 3., 4., 1.],
         [2., 4., 4., 3., 4., 4.],
         [0., 2., 3., 1., 2., 1.]]])

In [38]:
max_pool_layer = nn.MaxPool2d(kernel_size=2) # default stride = 2

In [39]:
output = max_pool_layer(input)
output

tensor([[[3., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])

#Flatten


In [42]:
input = torch.randint(
    high = 5,
    size = (6,6),
    dtype = torch.float32
)
input

tensor([[3., 2., 3., 1., 2., 3.],
        [1., 3., 1., 2., 1., 4.],
        [2., 4., 2., 4., 2., 0.],
        [0., 2., 4., 1., 2., 4.],
        [3., 2., 2., 1., 4., 0.],
        [2., 3., 1., 1., 0., 2.]])

In [43]:
output = nn.Flatten(input)
output

Flatten(
  start_dim=tensor([[3., 2., 3., 1., 2., 3.],
          [1., 3., 1., 2., 1., 4.],
          [2., 4., 2., 4., 2., 0.],
          [0., 2., 4., 1., 2., 4.],
          [3., 2., 2., 1., 4., 0.],
          [2., 3., 1., 1., 0., 2.]]), end_dim=-1
)

In [44]:
flatten_layer = nn.Flatten()
output = flatten_layer(input)
output

tensor([[3., 2., 3., 1., 2., 3.],
        [1., 3., 1., 2., 1., 4.],
        [2., 4., 2., 4., 2., 0.],
        [0., 2., 4., 1., 2., 4.],
        [3., 2., 2., 1., 4., 0.],
        [2., 3., 1., 1., 0., 2.]])