## pytorch

In [ ]:
import torch
import numpy as np

 # Image Example
N, C, H, W = 1, 2, 2, 2
data =  np.zeros((N, C, H, W))
data[0,0,:,:] = np.array([[8, 6],
                          [2, 4]])
data[0,1,:,:] = np.array([[0, 2],
                          [1, 5]])

data = data.reshape(N, C, H, W)
print(data.shape)
print(data[0,0,:,:])
print(data[0,1,:,:])

(1, 2, 2, 2)
[[8. 6.]
 [2. 4.]]
[[0. 2.]
 [1. 5.]]


In [ ]:
input = torch.tensor(data,dtype=torch.float)
layer_norm = torch.nn.LayerNorm([C, H, W])
output = layer_norm(input)
print(output)

tensor([[[[ 1.7650,  0.9806],
          [-0.5883,  0.1961]],

         [[-1.3728, -0.5883],
          [-0.9806,  0.5883]]]], grad_fn=<NativeLayerNormBackward0>)


## self-implementation

In [ ]:
import numpy as np

N, C, H, W = 1, 2, 2, 2
data =  np.zeros((N, C, H, W))
data[0,0,:,:] = np.array([[8, 6],
                          [2, 4]])
data[0,1,:,:] = np.array([[0, 2],
                          [1, 5]])
data = data.reshape(1, 2, 2, 2)  #H, W, C
print(data.shape)
print(data[0,:,:,0])
print(data[0,:,:,1])

(1, 2, 2, 2)
[[8. 2.]
 [0. 1.]]
[[6. 4.]
 [2. 5.]]


In [ ]:
eps = 0.0 #1e-5

mean = data.mean(axis=(1, 2, 3))
std  = np.sqrt(data.var(axis=(1, 2, 3)) + eps)

print(mean)
print(std)

[3.5]
[2.54950976]


In [ ]:
output = (data - mean) / std
print(data[0,0,:,:])
print(data[0,1,:,:])

[[8. 6.]
 [2. 4.]]
[[0. 2.]
 [1. 5.]]
